### ISSUE TITLE
BUG. No default nrmlvo entry found.

### ISSUE THREAD

**Issue by MoritzWeber0** [udevbe/greenfield#83] opened 2021-08-16 13:52 UTC
When I try to run the greenfield demo, I get the following error (in the browser console, `Keyboard.ts:46` from `compositor-module/src`): 
```Uncaught (in promise) Error: BUG. No default nrmlvo entry found.``` 

`langTokens` are `["en", "US"]`
The `nrmlvoEntries` Variable is an empty list (`buildNrmlvoEntries` returns an empty list as well) and therefore `nrmlvoEntry` is undefined. 

The file `/usr/local/share/X11/xkb/rules/evdev.lst` does not exist on my system. 

Thanks for any help in advance!

**Comment by Zubnix** [comment] 2021-08-17 14:48
I'm currently updating the README.md of the greenfield-cloud branch, as that one is a bit more up to date and has more development going on, which will hopefully solve your issue. I'll merge that branch into master in the next couple of hours/days.

**Comment by MoritzWeber0** [comment] 2021-08-17 15:06
Thank you! I got it running with this docker configuration: https://github.com/udevbe/webshell
I tried the Docker demo of the branch `test-framework` as well, however, I had the same issue there.

**Comment by Zubnix** [comment] 2021-08-18 07:44
I've updated the readme on the greenfield-cloud branch. This should give you the latest up to date version. Can you confirm this works for you?

**Comment by MoritzWeber0** [comment] 2021-08-18 10:32
Thanks, I will probably only get back to it in the next few days/weeks. I will then comment whether it worked.

**Comment by Zubnix** [comment] 2021-09-22 14:06
closing because can't reproduce. please re-open if you encounter any issues.

**Closed by Zubnix** 2021-09-22 14:06 UTC
